language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
install:
  - 'pip install -r tribus/config/data/python-dependencies.list'
  - 'pip install coveralls'
script:
  - 'python setup.py test'
  - 'coverage run --source=tribus setup.py test'
after_success:
  - coveralls