#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: @PAQUETE@
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) @YEAR@ @AUTHOR_NAME@ <@AUTHOR_MAIL@>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="@PAQUETE@"

case ${1} in

	install|upgrade)

	# Aquí va lo que el paquete debe configurar/crear/borrar antes de
	# instalarse. Lenguaje a usar: BASH.

	;;

        abort-upgrade)

        # Aquí va lo que el paquete debe configurar/crear/borrar si se
        # aborta el proceso de actualizar un paquete a una versión superior.
	# Lenguaje a usar: BASH.

        ;;

        *)
                echo "preinst no reconoce el argumento '"${1}"'" >&2
                exit 1
        ;;

esac

#DEBHELPER#

exit 0
