#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-desarrollador
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#	      mantenedor, de forma tal de asegurarse que el sistema quede
#	      como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-desarrollador"

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	#for usuario in /home/*? ; do
		#rm -rf ${usuario}/Escritorio/manual-desarrollador.desktop
	#done

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
