#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-desarrollador
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-desarrollador"

case ${1} in

	configure)
	# Para cada usuario en /home/ ...
	for usuario in /home/*? ;
	do

		# Obteniendo sólo el nombre del usuario
		usuario_min=$(basename ${usuario})

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		case  $(grep "${usuario_min}:.*:.*:.*:.*:.*:::" /etc/shadow) in

			'')
			# No hace nada si no se encuentra en /etc/shadow
			;;

			*)

				# Asegurando que el directorio .config/canaima-desarrollador esté creado
				mkdir -p /home/${usuario_min}/.config/canaima-desarrollador/
				# con permisos apropiados
				chown ${usuario_min}:${usuario_min} /home/${usuario_min}/.config/canaima-desarrollador/
				#if [ -e /home/${usuario_min}/Escritorio/ ]; then
				# Copiamos el lanzador de escritorio al escritorio de cada usuario
				#cp /etc/skel/Escritorio/manual-desarrollador.desktop /home/${usuario_min}/Escritorio/
				# con permisos apropiados
				#chown ${usuario_min}:${usuario_min} /home/${usuario_min}/Escritorio/manual-desarrollador.desktop
				#fi
				# Copia del archivo de configuración si determina que no existe
				if [ ! -e /home/${usuario_min}/.config/canaima-desarrollador/usuario.conf ]; then
					cp /etc/skel/.config/canaima-desarrollador/usuario.conf /home/${usuario_min}/.config/canaima-desarrollador/
					# con permisos apropiados
					chown ${usuario_min}:${usuario_min} /home/${usuario_min}/.config/canaima-desarrollador/usuario.conf
				fi
			;;
		esac

	done

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		echo "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
