#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: @PAQUETE@
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) @YEAR@ @AUTHOR_NAME@ <@AUTHOR_MAIL@>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

        # Aquí va lo que el paquete debe configurar/crear/borrar después de
        # removerse. Lenguaje a usar: BASH.

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
